version: '3.8'

services:
  cfb:
    image: python:3.10  # 指定Python镜像，这里使用了3.9版本，可以根据需要更改
    volumes:
      - .:/app  
    working_dir: /app/caifubao-backend  # 设置工作目录为/app
    command: python manage.py  # 运行Python应用的命令，根据你的应用入口文件调整
    ports:
      - "5000:5000"  # 将容器的5000端口映射到宿主机的5000端口，根据你的应用端口调整
    environment:
      - MONGO_URL=mongodb://mongo_db:27017  # 设置环境变量，指向MongoDB服务
    depends_on:
      - mongo_db  # 确保Python应用依赖于MongoDB服务

  mongo_db:
    image: mongo  # 使用官方MongoDB镜像
    volumes:
      - mongo_data:/data/db  # 将MongoDB数据卷挂载到宿主机的目录，这里定义了一个名为mongo_data的卷
    ports:
      - "27017:27017"  # 将MongoDB容器的27017端口映射到宿主机的27017端口
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  # 设置MongoDB的root用户名
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}  # 设置MongoDB的root密码，建议在实际使用中更改

volumes:
  mongo_data:  # 定义一个名为mongo_data的数据卷，用于持久化MongoDB数据
