# This patch suspends all datahub CronJobs in the dev environment.
# Remove this patch to enable cronjobs for testing.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: caifubao-datahub-quote-index
spec:
  suspend: true
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: caifubao-datahub-quote-stock
spec:
  suspend: true
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: caifubao-datahub-signal
spec:
  suspend: true
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: caifubao-datahub-scoring
spec:
  suspend: true
