from mongoengine import (
    DateTimeField,
    Document,
    DynamicDocument,
    FloatField,
    ReferenceField,
    GenericLazyReferenceField,
    StringField,
)

from app.model.stock import BasicStock


class FactorDataEntry(DynamicDocument):
    """
    Legacy long-table factor values.

    New datahub MA generation writes to StockFactorDaily, but this model remains
    available for older cleanup and read paths during the migration window.
    """

    meta = {
        "collection": "factor_data_entry",
        "indexes": [
            {"fields": ["name", "stock_code", "date"], "unique": True},
            "date",
            ("name", "target_code"),
        ],
    }
    name = StringField()
    stock = ReferenceField(BasicStock)
    stock_name = StringField()
    stock_code = StringField()
    category = StringField()
    date = DateTimeField()
    value = FloatField()


class StockFactorDaily(Document):
    """
    Wide daily factor values generated by datahub.
    """

    meta = {
        "collection": "stock_factor_daily",
        "indexes": [
            {"fields": ["stock_code", "date"], "unique": True},
            ("stock_code", "-date"),
            "-date",
        ],
    }
    stock = GenericLazyReferenceField()
    stock_name = StringField()
    stock_code = StringField(required=True)
    category = StringField(default="stock")
    date = DateTimeField(required=True)
    ma_10 = FloatField()
    ma_20 = FloatField()
    ma_30 = FloatField()
    ma_60 = FloatField()
    ma_120 = FloatField()
