apiVersion: apps/v1
kind: Deployment
metadata:
  name: caifubao-backend
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: MONGODB_PASS
          valueFrom:
            secretKeyRef:
              name: prod-mongodb-pass-secret
              key: MONGODB_PASSWORD
