apiVersion: apps/v1
kind: Deployment
metadata:
  name: caifubao-backend
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_SECRET_KEY
        - name: SECURITY_PASSWORD_SALT
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: SECURITY_PASSWORD_SALT
