apiVersion: apps/v1
kind: Deployment
metadata:
  name: caifubao-datahub
spec:
  template:
    spec:
      containers:
      - name: datahub
        env:
        - name: MONGODB_PASS
          valueFrom:
            secretKeyRef:
              name: prod-mongodb-pass-secret
              key: PROD_MONGODB_PASS
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: caifubao-datahub-quote-index
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: quote-index-runner
            env:
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: prod-mongodb-pass-secret
                  key: PROD_MONGODB_PASS
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: caifubao-datahub-quote-stock
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: quote-stock-runner
            env:
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: prod-mongodb-pass-secret
                  key: PROD_MONGODB_PASS
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: caifubao-datahub-signal
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: signal-runner
            env:
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: prod-mongodb-pass-secret
                  key: PROD_MONGODB_PASS
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: caifubao-datahub-scoring
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scoring-runner
            env:
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: prod-mongodb-pass-secret
                  key: PROD_MONGODB_PASS
