from mongoengine import (
    Document,
    DynamicDocument,
    StringField,
    DateTimeField,
    ReferenceField,
    FloatField,
    GenericLazyReferenceField,
)
from app.model.stock import BasicStock


class FactorDataEntry(DynamicDocument):
    """
    category: stock, market
    """

    meta = {
        "indexes": [
            {"fields": ["name", "stock_code", "date"], "unique": True},
            "date",
            ("name", "target_code"),
        ]
    }
    name = StringField()
    stock = ReferenceField(BasicStock)
    stock_name = StringField()
    stock_code = StringField()
    category = StringField()
    date = DateTimeField()
    value = FloatField()


class StockFactorDaily(Document):
    """
    Wide daily factor values generated by datahub.

    The datahub image build copies backend models into datahub before building,
    so this model must exist on both sides.
    """

    meta = {
        "collection": "stock_factor_daily",
        "indexes": [
            {"fields": ["stock_code", "date"], "unique": True},
            ("stock_code", "-date"),
            "-date",
        ],
    }
    stock = GenericLazyReferenceField()
    stock_name = StringField()
    stock_code = StringField(required=True)
    category = StringField(default="stock")
    date = DateTimeField(required=True)
    ma_10 = FloatField()
    ma_20 = FloatField()
    ma_30 = FloatField()
    ma_60 = FloatField()
    ma_120 = FloatField()
